[package]
name = "atom_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
serde = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

atom_infrastructure = { path = "../infrastructure" }
